### ISSUE TITLE
Links clickable

### ISSUE THREAD

**Issue by hodel33** [yy0931/sqlite3-editor#16]
I wonder if it's possible to make it so that you can actually click on links?
Either in the actual column view or/and under the table view in the info section.
Would help my workflow greatly!

![image](https://user-images.githubusercontent.com/112579590/230380066-441601e7-5221-480b-9a23-55bd1a524288.png)

**Comment by yy0931** [comment]
Yes, the easiest way to implement it should be to add a functionality to open a link with ctrl+click on a cell. I'll work on it.

**Comment by hodel33** [comment]
> Yes, the easiest way to implement it should be to add a functionality to open a link with ctrl+click on a cell. I'll work on it.

Yeah, thought of the Ctrl+Click thing. Would be so lovely! Thx, ur the best! :)

**Comment by hodel33** [comment]
I think something happened just now with your extension? Hiding the info box under the tables + weird scroll behavior.. did you update something just now? or is it just me..

**Comment by hodel33** [comment]
Hmm now the whole Search function is broken.. did you do anything?

**Comment by yy0931** [comment]
The extension has not been updated since 3/30/2023. You can check it in the "Version History" tab at https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor.
Can you explain how it is broken? If it's frozen, there might be errors in the Console tab in `>Developer: Open Webview Developer Tools`.

**Comment by hodel33** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/112579590/230746987-52caaa0a-8716-44f3-8516-0a1efed5c52c.png)

What happens is that if you click Search or hit Ctrl+F it gets activated (the button) but no Search window show up anymore. Its just completely gone. Tried many times. Search function is broken, dont know why.. randomly happened

![image](https://user-images.githubusercontent.com/112579590/230747017-58ef0a89-a57b-4a36-8664-3f76249ad92b.png)

**Comment by yy0931** [comment]
Have you tried reopening the VSCode windows? The error does not seem to be raised by the extension, but by VSCode.
I am currently reading related issues including https://github.com/microsoft/vscode/issues/161730 and https://github.com/microsoft/vscode/issues/79949.

**Comment by hodel33** [comment]
> Have you tried reopening the VSCode windows? The error does not seem to be raised by the extension, but by VSCode. I am currently reading related issues including [microsoft/vscode#161730](https://github.com/microsoft/vscode/issues/161730) and [microsoft/vscode#79949](https://github.com/microsoft/vscode/issues/79949).

Yeah I've restarted it many times already.. so weird. And that Search function is really important to me.

Btw another thing I thought about is that it would be cool if a whole row would be marked when youve clicked on any of the values on the row. Like a little darker BG color than the one marked. Would be awesome since I work in big tables.

**Comment by yy0931** [comment]
I've fixed a bug that I encountered when I repeatedly clicked the find button and switched tables. I've published v1.0.73; could you check if it fixes the issue? v1.0.73 also includes the ctrl+click feature.

> whole row would be marked when youve clicked...

That is a small style change, so it's easy. Feel free to suggest any other ideas.

**Comment by hodel33** [comment]
> I've fixed a bug that I encountered when I repeatedly clicked the find button and switched tables. I've published v1.0.73; could you check if it fixes the issue? v1.0.73 also includes the ctrl+click feature.
> 
> > whole row would be marked when youve clicked...
> 
> That is a small style change, so it's easy. Feel free to suggest any other ideas.

Ahh lovely! Will love that fix, since it will make it so much clearer on which row one is at (current row view) :)

Clickable links work great now! Thx man!
Hmm that Search box error is still there. No box to be found anywhere.. so strange!

**Comment by yy0931** [comment]
I could not reproduce the issue. Can you think of any reason for it? Like a large table or remote-ssh.

In addition, what does $("#findWidget") print in the DevTools console for `index.html` when the `Find` toggle button is enabled? Is the element there?

![Screenshot from 2023-04-09 09-57-56](https://user-images.githubusercontent.com/54441600/230748830-4872258f-08c0-44e8-bc5a-dba1a3b920e0.png)

![image](https://user-images.githubusercontent.com/54441600/230748645-741d5a1a-3672-46e4-8f73-5683f44260b7.png)

**Comment by yy0931** [comment]
I could reproduce it, though it may be another bug different from yours.

**Comment by yy0931** [comment]
The bug should be fixed in v1.0.74. There was an issue where the editor state was saved in an incorrect format.

**Comment by hodel33** [comment]
> The bug should be fixed in v1.0.74. There was an issue where the editor state was saved in an incorrect format.

You f* did it man! And added the lovely bg thing for a whole row when a value is marked. I wanna kiss you haha. So awesome now! 😃
